### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by LoseYouNow** [Sentient111/KernelDrawing#4]
[<] Loading vulnerable driver, Name: uZYCpkMTNOmLNdbkGazLlavklumXr
[+] NtLoadDriver Status 0x0
[+] PiDDBLock Ptr 0xfffff8016c3479a0
[+] PiDDBCacheTable Ptr 0xfffff8016c347adc
[+] PiDDBLock Locked
[+] Found Table Entry = 0xFFFF8204B0CDAAF0
[+] PiDDBCacheTable Cleaned
[+] g_KernelHashBucketList Found 0xFFFFF8016D0AC080
[+] g_HashCacheLock Locked
[+] Found In g_KernelHashBucketList: uZYCpkMTNOmLNdbkGazLlavklumXr
[+] g_KernelHashBucketList Cleaned
[+] MmUnloadedDrivers Cleaned: uZYCpkMTNOmLNdbkGazLlavklumXr
[-] Invalid format of PE image
[-] Failed to map CheatDriver.sys !!!!!!!!!!!!!!!!!!
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0x0
[+] Vul driver data destroyed before unlink

**Comment by LoseYouNow** [comment]
failed to run it

**Comment by pr0pheit** [comment]
user issue

case closed

**Comment by Sentient111** [comment]
Seems like a visual studio issue to me
